Failure # 1 (occurred at 2024-12-23_14-12-06)
[36mray::_Inner.train()[39m (pid=61740, ip=172.26.204.107, actor_id=dd663f75c305bc66f461c0de01000000, repr=TorchTrainer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/air/_internal/util.py", line 107, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/train/base_trainer.py", line 799, in _trainable_func
    super()._trainable_func(self._merged_config)
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/train/base_trainer.py", line 107, in _train_coordinator_fn
    trainer.training_loop()
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/train/data_parallel_trainer.py", line 459, in training_loop
    backend_executor.start()
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/train/_internal/backend_executor.py", line 203, in start
    self._backend.on_start(self.worker_group, self._backend_config)
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/train/torch/config.py", line 200, in on_start
    ray.get(setup_futures)
           ^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.RayTaskError(ValueError): [36mray::_RayTrainWorker__execute._setup_torch_process_group()[39m (pid=61941, ip=172.26.204.107, actor_id=48a3c95f51eb3abb4e2d4c1c01000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7fd72743e120>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/train/_internal/worker_group.py", line 33, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/train/_internal/worker_group.py", line 30, in __execute
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/ray/train/torch/config.py", line 115, in _setup_torch_process_group
    dist.init_process_group(
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 97, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1527, in init_process_group
    default_pg, _ = _new_process_group_helper(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/study/kserving/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1771, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(
                    ^^^^^^^^^^^^^^^^^
ValueError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
